{
 "title": "Vertica Overview (Prometheus)",
 "description": "General cluster overview. This dashboard is designed to be the initial landing page in Grafana.",
 "tags": [ "vertica-eon" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "db_name", "label": "Databases", "query": { "query": "vertica_db_info" } },
   {
    "name": "subcluster_name",
    "label": "Subcluster Name",
    "query": {
     "query": "vertica_subcluster_info{revive_instance_id=\"$db_name\"}"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "vertica_total_nodes_count{revive_instance_id=\"$db_name\",subcluster_oid=~\"$subcluster_name\"}"
    }
   },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values(vertica_resource_pool_memory_size_actual_kb,pool_name)"
    }
   },
   { "name": "request_type", "label": "Request Type", "query": { "query": "label_values(request_type)" } },
   { "name": "storage_usage", "label": "Storage Usage", "query": { "query": "label_values(storage_usage)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.vertica.com/wp-content/uploads/2017/09/vertica_wht_rgb@2x.png\"/>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "description": "The total number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vertica_total_nodes_count{revive_instance_id=~\"$db_name\"})"
    }
   ]
  },
  {
   "title": "Up Nodes",
   "type": "gauge",
   "description": "Reports the number of up nodes in the cluster. ",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vertica_up_nodes_count{revive_instance_id=~\"$db_name\"})",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Read-Only Nodes",
   "type": "stat",
   "description": "Reports the number of read-only nodes in the cluster, when the cluster is in read-only mode. ",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vertica_is_readonly{revive_instance_id=~\"$db_name\"})",
     "legendFormat": "Read-Only"
    }
   ]
  },
  {
   "title": "Nodes With Disk Space Usage  > 60% (Low)",
   "type": "stat",
   "description": "The number of nodes with low disk space available for the selected storage usage.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by(node_name) (vertica_disk_storage_free_percent{revive_instance_id=~\"$db_name\",storage_usage=~\"$storage_usage\"} < 40))",
     "legendFormat": "{{storage_usage}}"
    }
   ]
  },
  {
   "title": "License Size",
   "type": "stat",
   "description": "If license limits the size of the database, this indicates how many MB the license is for.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vertica_license_size_mb{revive_instance_id=~\"$db_name\"})",
     "legendFormat": "License Size"
    }
   ]
  },
  {
   "title": "License Node Count",
   "type": "stat",
   "description": "If license limits the number of nodes in the database, this indicates how many nodes are allowed",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vertica_license_node_count{revive_instance_id=~\"$db_name\"}>0)",
     "legendFormat": "License Node Count"
    }
   ]
  },
  {
   "title": "Last Audit Ending Time",
   "type": "stat",
   "description": "The ending time of the last audit",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vertica_last_audit_end_time{revive_instance_id=~\"$db_name\"}>0) + (2451545-2440588)*(1000000*60*60*24)/1000",
     "legendFormat": "Last Audit Ending Time"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Shows Vertica build version.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vertica_build_info{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Compressed Total Data Size",
   "type": "stat",
   "description": "The total compressed size of the data.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vertica_data_size_compressed_mb{revive_instance_id=~\"$db_name\"})",
     "legendFormat": "Compressed Total Data Size"
    }
   ]
  },
  {
   "title": "Attempted Query Requests",
   "type": "stat",
   "description": "The number of attempted query requests.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_query_requests_attempted_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[$__range]))",
     "legendFormat": "Attempted"
    }
   ]
  },
  {
   "title": "Query Requests Processed Rows",
   "type": "stat",
   "description": "The number of processed queries rows over the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_query_requests_processed_rows_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[$__range]))",
     "legendFormat": "processed rows"
    }
   ]
  },
  {
   "title": "Completed Query Requests",
   "type": "stat",
   "description": "The number of completed query requests.",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_query_requests_succeeded_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[$__range]))",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Estimated Total Data Size",
   "type": "stat",
   "description": "An estimation, in megabytes, of the total data size of the raw data. This is computed each time there is an audit.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vertica_estimated_data_size_raw_mb{revive_instance_id=~\"$db_name\"})",
     "legendFormat": "Estimated Total Data Size"
    }
   ]
  },
  {
   "title": "Queued Queries (Database)",
   "type": "stat",
   "description": "The number of queued query requests.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vertica_queued_requests_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=\"general\"})",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "Running Queries (Database)",
   "type": "stat",
   "description": "The number of running queries.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vertica_resource_pool_running_query_count{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=\"general\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Failed Query Requests",
   "type": "stat",
   "description": "The number of failed query requests over the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_query_requests_failed_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[$__range]))",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The number of errors over the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_errors{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",error_level=~\"ERROR|FATAL|PANIC\"}[$__range]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Locked Users",
   "type": "stat",
   "description": "The number of locked users.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vertica_locked_users{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "Locked Users"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cluster Health",
   "type": "timeseries",
   "description": "Monitors cluster health status by tracking the number of up nodes and read-only nodes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(vertica_up_nodes_count{revive_instance_id=~\"$db_name\"})",
     "legendFormat": "Up Node Count"
    },
    {
     "expr": "sum(vertica_is_readonly{revive_instance_id=~\"$db_name\"})",
     "legendFormat": "Read-Only Node Count"
    }
   ]
  }
 ]
}