{
 "title": "Vertica Depot (Prometheus)",
 "description": "Details about depot usage.",
 "tags": [ "vertica-eon" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "db_name", "label": "Database", "query": { "query": "vertica_db_info" } },
   {
    "name": "subcluster_name",
    "label": "Subcluster Name",
    "query": {
     "query": "vertica_subcluster_info{revive_instance_id=\"$db_name\"}"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "vertica_total_nodes_count{revive_instance_id=\"$db_name\",subcluster_oid=~\"$subcluster_name\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.vertica.com/wp-content/uploads/2017/09/vertica_wht_rgb@2x.png\"/>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Current Depot Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Depot's Fetch Queue",
   "type": "stat",
   "description": "Total depot space currently in use, on all nodes in the database added together.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum by(node_name) (vertica_depot_fetch_queue_size{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}))",
     "legendFormat": "Depot's Fetch Queue"
    }
   ]
  },
  {
   "title": "Usage by Node",
   "type": "table",
   "description": "Lists the number of bytes in the depot and percentage used, for each node in the database.",
   "gridPos": { "h": 6, "w": 18, "x": 5, "y": 3 },
   "targets": [
    {
     "expr": "sum by(node_name) (vertica_depot_size_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})"
    },
    {
     "expr": "sum by(node_name,subcluster_name)(vertica_subcluster_info{revive_instance_id=\"$db_name\",node_name=~\"$node_name\"})"
    },
    {
     "expr": "sum by(node_name) (vertica_depot_fetch_queue_size{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Depot in Use",
   "type": "stat",
   "description": "Total depot space currently in use, on all nodes in the database added together.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum by(node_name) (vertica_depot_size_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}))",
     "legendFormat": "Depot in Use"
    }
   ]
  },
  { "title": "Depot Lookup Hits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Look up Requests",
   "type": "stat",
   "description": "The number of lookup  requests during the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_depot_lookup_requests_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Depot Lookup Hits %",
   "type": "gauge",
   "description": "Percentage of cache hit when finding a file in the depot.",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 *(sum(increase(vertica_depot_lookup_hits_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range]))) / (sum(increase(vertica_depot_lookup_requests_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range])) > 0)",
     "legendFormat": "Hits %"
    }
   ]
  },
  {
   "title": "Look up Hits",
   "type": "stat",
   "description": "The Number of cache hits when finding a file in the depot.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_depot_lookup_hits_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range]))"
    }
   ]
  },
  { "title": "Depots Fetches and Evictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Attempted Depot Fetches",
   "type": "stat",
   "description": "The total number of depot fetches during select time range.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_depot_fetches_requests_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",source=\"communal\"}[$__range]))",
     "legendFormat": "Attempted"
    }
   ]
  },
  {
   "title": "Completed Depot Fetches and Evictions",
   "type": "timeseries",
   "description": "Shows how the fetches and eviction sizes increase over time. Each point refers to the increase over the past 5 min.",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase((vertica_depot_fetches_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",source=\"communal\"}[5m]))) ",
     "legendFormat": "Fetches"
    },
    {
     "expr": "sum(increase(vertica_depot_evictions_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Evictions"
    }
   ]
  },
  {
   "title": "Depot Fetches Time Distribution",
   "type": "heatmap",
   "description": "Shows the number of new depot fetches, for each bucket, over time.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "sum by (le) (increase(vertica_depot_fetches_ms_bucket{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",source=\"communal\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Failed Fetches %",
   "type": "stat",
   "description": "Percentage of failed depot fetches during the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (sum(increase(vertica_depot_fetches_failures_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",source=\"communal\"}[$__range])) / sum(increase(vertica_depot_fetches_requests_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",source=\"communal\"}[$__range]) > 0) )",
     "legendFormat": "Failed Fetches %"
    }
   ]
  },
  {
   "title": "Running/Queued Uploads from Depot to Communal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Uploads in Progress",
   "type": "stat",
   "description": "Shows the number of requests currently uploading a file to communal storage through the depot.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vertica_depot_uploads_in_progress_counter{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "Uploads in Progress"
    }
   ]
  },
  {
   "title": "Uploads in Progress's Size",
   "type": "stat",
   "description": "Shows the number of bytes in running requests that are uploading a file to communal storage through the depot.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vertica_depot_uploads_in_progress_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "Uploads in Progress Bytes"
    }
   ]
  },
  {
   "title": "Running/Queued Uploads",
   "type": "timeseries",
   "description": "Shows the number of running/queued uploads over time.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(vertica_depot_uploads_in_progress_counter{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}) or on() vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(vertica_depot_uploads_queued_counter{revive_instance_id=~\"$db_name\"}) or on() vector(0)",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "Queued Uploads",
   "type": "stat",
   "description": "Shows the number of queued requests to upload a file to communal storage through the depot.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vertica_depot_uploads_queued_counter{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "Queued Uploads"
    }
   ]
  },
  {
   "title": "Queued Uploads' Size",
   "type": "stat",
   "description": "Shows the number of bytes in queued requests to upload a file to communal storage through the depot.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vertica_depot_uploads_queued_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "Queued Uploads Bytes"
    }
   ]
  },
  { "title": "Uploads from Depot to Communal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Attempted Depot Uploads",
   "type": "stat",
   "description": "Shows the number of attempted depot uploads.\n\nOnly counted if UseDepotForWrites is enabled. Metric mirrors the dc_depot_uploads table.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_depot_uploads_requests_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range]))",
     "legendFormat": "Attempted"
    }
   ]
  },
  {
   "title": "Uploads Size",
   "type": "stat",
   "description": "Shows the number of bytes uploads from the depot to communal storage.\n\nOnly counted if UseDepotForWrites is enabled. Metric mirrors the dc_depot_uploads table.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(vertica_depot_uploads_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range]))",
     "legendFormat": "Uploads Size"
    }
   ]
  },
  {
   "title": "Uploads Size",
   "type": "timeseries",
   "description": "Shows how the number of bytes uploads from the depot to communal storage increases over time.\nEach point refers to the increase over the past 5 min.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(vertica_depot_uploads_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "Uploads Size"
    }
   ]
  },
  {
   "title": "Upload rate",
   "type": "timeseries",
   "description": "Shows how the number of bytes per second uploads from the depot to communal storage increases over time.\nEach point refers to the increase over the past 5 min.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "1000 * sum(increase(vertica_depot_uploads_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[5m])) or vector(0) / (sum(increase(vertica_depot_uploads_ms_sum{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[5m])) > 0 or vector(1))",
     "legendFormat": "Upload rate"
    }
   ]
  },
  {
   "title": "Successful Uploads %",
   "type": "stat",
   "description": "Shows the percentage of successful write when writing to communal storage through the depot.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (1 - sum(increase(vertica_depot_uploads_failures_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range])) / (sum(increase(vertica_depot_uploads_requests_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range]) > 0))) ",
     "legendFormat": "Successful Uploads %"
    }
   ]
  },
  {
   "title": "Upload rate",
   "type": "stat",
   "description": "Shows the number of bytes per second uploads from the depot to communal storage.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1000 * (sum(increase(vertica_depot_uploads_bytes{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range]))) / (sum(increase(vertica_depot_uploads_ms_sum{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[$__range]) > 0))",
     "legendFormat": "Upload rate"
    }
   ]
  }
 ]
}