{
 "title": "Queries",
 "description": "Detailed information about queries that are currently running in a cluster.",
 "tags": [ "vertica-eon" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "db_name", "label": "Databases", "query": { "query": "vertica_db_info" } },
   {
    "name": "subcluster_name",
    "label": "Subcluster Name",
    "query": {
     "query": "vertica_subcluster_info{revive_instance_id=\"$db_name\"}"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "vertica_total_nodes_count{revive_instance_id=\"$db_name\",subcluster_oid=~\"$subcluster_name\"}"
    }
   },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values(vertica_resource_pool_memory_size_actual_kb,pool_name)"
    }
   },
   { "name": "request_type", "label": "Request Type", "query": { "query": "label_values(request_type)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.vertica.com/wp-content/uploads/2017/09/vertica_wht_rgb@2x.png\"/>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Attempted Query Requests",
   "type": "timeseries",
   "description": "This shows the increase rate of  the number of attempted requests. Each point represents the attempted requests per second over the past 5 min.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(vertica_query_requests_succeeded_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[5m]))",
     "legendFormat": "Attempted"
    }
   ]
  },
  {
   "title": "Processed Rows ",
   "type": "timeseries",
   "description": " This shows the increase rate of the number of processed rows. Each point represents the processed rows per second over the past 5 min.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(vertica_query_requests_processed_rows_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[5m]))",
     "legendFormat": "Processed Rows"
    }
   ]
  },
  {
   "title": "Completed /Failed Requests",
   "type": "timeseries",
   "description": "Displays how  fast completed and failed query requests increase. Each point represents the completed/failed requests per second over the past 5 min.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(vertica_query_requests_succeeded_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",request_type=~\"$request_type\"}[5m])) or on() vector(0)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(rate(vertica_query_requests_failed_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"}[5m])) or on() vector(0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Running/Queued requests",
   "type": "timeseries",
   "description": "Shows how the numbers of running and queued queries change over time.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(vertica_resource_pool_running_query_count{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\"}) or on() vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(vertica_queued_requests_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\"}) or on() vector(0)",
     "legendFormat": "Queued"
    }
   ]
  },
  { "title": "Query Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Completed (by node)",
   "type": "bargauge",
   "description": "The number of completed query requests by node  over time.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(node_name) (increase(vertica_query_requests_succeeded_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\"}[$__range]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Failed (by node)",
   "type": "bargauge",
   "description": "The total number of failed query requests by node  over time.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(node_name) (increase(vertica_query_requests_failed_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\"}[$__range]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Completed (by pool)",
   "type": "bargauge",
   "description": "The number of completed query requests by node  over time.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(pool_name) (increase(vertica_query_requests_succeeded_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\"}[$__range]))",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Failed (by pool)",
   "type": "bargauge",
   "description": "The total number of failed query requests by pool over time.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(pool_name) (increase(vertica_query_requests_failed_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\"}[$__range]))",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "User Query Type Distribution",
   "type": "timeseries",
   "description": "This shows the increase of query requests distributed over request types. Each point represents the attempted requests over the past 5 min. Only queries executed during the selected time range are considered.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(request_type) (increase(vertica_query_requests_attempted_total{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",request_type=~\"$request_type\"}[5m]))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Average Execution Time per Type",
   "type": "timeseries",
   "description": "The time it takes in average for the execution of a single query distributed per type. Only queries executed during the selected time range are considered.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (request_type)(increase(vertica_query_requests_time_ms_sum{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[5m])) / (sum by(request_type)(increase(vertica_query_requests_time_ms_count{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[5m]) ) > 0 or vector(1))\r\nor\r\nsum by (request_type)(increase(vertica_query_requests_time_ms_sum{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[5m]))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Query Execution Time Distribution",
   "type": "heatmap",
   "description": "Shows the number of queries, for each time range, over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (le) (increase(vertica_query_requests_time_ms_bucket{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\",pool_name=~\"$pool_name\",request_type=~\"$request_type\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}