{
 "title": "Vertica Resource Management",
 "description": "Provides insight into the usage of the various resource pools",
 "tags": [ "vertica" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "db_name", "label": "Database", "query": { "query": "vertica_db_info" } },
   {
    "name": "subcluster_name",
    "label": "Subcluster Name",
    "query": {
     "query": "vertica_subcluster_info{revive_instance_id=\"$db_name\"}"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "vertica_total_nodes_count{revive_instance_id=\"$db_name\",subcluster_oid=~\"$subcluster_name\"}"
    }
   },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values(vertica_resource_pool_memory_size_actual_kb,pool_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.vertica.com/wp-content/uploads/2017/09/vertica_wht_rgb@2x.png\"/>"
   },
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \naverage_cpu_usage_percent \nFROM \nv_monitor.cpu_usage \nWHERE \n$__timeFilter(end_time)"
    }
   ]
  },
  {
   "title": "Pool Configuration Values for $pool_name pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Planned Concurrency",
   "type": "stat",
   "description": "The preferred number of queries that execute concurrently in this resource pool.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vertica_resource_pool_planned_concurrency{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "Planned Concurrency"
    }
   ]
  },
  {
   "title": "Maximum Concurrency",
   "type": "stat",
   "description": "The maximum number of concurrent execution slots available to the resource pool.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vertica_resource_pool_max_concurrency{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}>=0)",
     "legendFormat": "Maximum Concurrency"
    }
   ]
  },
  {
   "title": "Maximum Memory (MB)",
   "type": "stat",
   "description": "Value assigned as the maximum size (in MegaBytes) this resource pool can grow by borrowing memory from the GENERAL pool.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vertica_resource_pool_max_memory_size_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}) / 1024",
     "legendFormat": "Maximum Memory"
    }
   ]
  },
  {
   "title": "Maximum Query Memory (MB)",
   "type": "stat",
   "description": "The maximum amount of memory allocated by this pool to process any query. Value, in MegaBytes, of the MAXQUERYMEMORYSIZE parameter as defined for the pool.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(vertica_resource_pool_max_query_memory_size_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}) / 1024) > 0 or on() vector(0)",
     "legendFormat": "Maximum Query Memory"
    }
   ]
  },
  {
   "title": "Priority",
   "type": "stat",
   "description": "Specifies priority of queries in this pool when they compete for resources in the GENERAL pool.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vertica_resource_pool_priority{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "Priority"
    }
   ]
  },
  {
   "title": "Runtime Priority Threshold",
   "type": "stat",
   "description": "Limits in seconds how soon a query must finish before the Resource Manager assigns to it the resource pool's RUNTIMEPRIORITY setting.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vertica_resource_pool_runtime_priority_threshold{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "Runtime Priority Threshold"
    }
   ]
  },
  {
   "title": "Queue Timeout",
   "type": "stat",
   "description": "The maximum length of time requests can wait for resources to become available before being rejected",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vertica_resource_pool_queue_timeout{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "Queue Timeout"
    }
   ]
  },
  {
   "title": "Current Pool Usage Activity (in average per node) for $pool_name pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Average Running Query Count",
   "type": "stat",
   "description": "The average number of queries per node currently executing in the pool.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vertica_resource_pool_running_query_count{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "Average Running Query Count"
    }
   ]
  },
  {
   "title": "Avg. General Memory",
   "type": "stat",
   "description": "The average amount of borrowed memory, per node, from the GENERAL pool by requests running against the pool.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vertica_resource_pool_general_memory_borrowed_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "Avg. General Memory"
    }
   ]
  },
  {
   "title": "Avg.  Memory for Queued Requests",
   "type": "stat",
   "description": "The average amount of memory per node,  for all queued requests in the pool.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vertica_queued_requests_total_memory_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "Avg.  Memory for Queued Requests"
    }
   ]
  },
  {
   "title": "Queueing Threshold (MB)",
   "type": "stat",
   "description": "When the amount of memory (in MegaBytes) used by all requests against this resource pool exceeds this, new requests against the pool are queued until memory becomes available.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vertica_resource_pool_queueing_threshold_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}) / 1024",
     "legendFormat": "Queueing Threshold"
    }
   ]
  },
  {
   "title": "Memory Used %",
   "type": "gauge",
   "description": "Percentage of memory used in a pool.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(vertica_resource_pool_memory_inuse_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}) / sum(vertica_resource_pool_max_memory_size_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "Memory Used %"
    }
   ]
  },
  {
   "title": "Avg. Query Budget (MB)",
   "type": "stat",
   "description": "The current amount of memory (in MegaBytes) that queries are tuned to use in the pool.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vertica_resource_pool_query_budget_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}>=0) / 1024 or vector(0)",
     "legendFormat": "Avg. Query Budget"
    }
   ]
  },
  {
   "title": "Resource Pool Statistics (in average per node) for $pool_name pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Resource Usage (MB)",
   "type": "timeseries",
   "description": "This shows how the Max Memory, Pool Memory and Free Memory in the pool change over time. Each of the values is an average per node.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(vertica_resource_pool_max_memory_size_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}) /1024",
     "legendFormat": "Maximum Memory Size"
    },
    {
     "expr": "avg(vertica_resource_pool_memory_size_actual_kb{pool_name=~\"$pool_name\"}) / 1024",
     "legendFormat": "Pool Memory Size"
    },
    {
     "expr": "(avg(vertica_resource_pool_max_memory_size_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}) - avg(vertica_resource_pool_memory_inuse_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})) / 1024",
     "legendFormat": "Average Free Memory"
    }
   ]
  },
  {
   "title": "Average Execution ",
   "type": "timeseries",
   "description": "The time it takes in average for the execution of a single query. \n Each point represents the average execution per query  over the past 5 min.\n",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(vertica_query_requests_time_ms_sum{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}[5m])) / sum(increase(vertica_query_requests_time_ms_count{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}[5m]))",
     "legendFormat": "Average Execution Time"
    }
   ]
  },
  {
   "title": "Resource Rejections",
   "type": "timeseries",
   "description": "Shows  how fast  resource rejections count increases per second. ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(vertica_resource_rejections_total{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}[5m])) or on() vector(0)",
     "legendFormat": "Resource Rejections"
    }
   ]
  },
  {
   "title": "Average Number of Running Queries",
   "type": "timeseries",
   "description": "The average number of running queries over time.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "avg(vertica_resource_pool_running_query_count{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "Average Number of Running Queries"
    }
   ]
  },
  { "title": "Summary Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Resource Uage Details by all Nodes",
   "type": "table",
   "description": "This table is a summary of resource usage for all nodes. With this you can get information about Pool Size, Max Memory... for each node. It is a complement to other panels that give averages per node. It captures just the last values.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(pool_name,node_name) (vertica_resource_pool_max_memory_size_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"} / 1024)",
     "legendFormat": "{{node_name}}.{{pool_name}}"
    },
    {
     "expr": "sum by(pool_name,node_name) (vertica_resource_pool_memory_size_actual_kb{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"} / 1024)",
     "legendFormat": "{{node_name}}.{{pool_name}}"
    },
    {
     "expr": "sum by(pool_name,node_name)(vertica_resource_pool_running_query_count{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})",
     "legendFormat": "{{node_name}}.{{pool_name}}"
    },
    {
     "expr": "sum by(pool_name,node_name)(\r\n\tvertica_queued_requests_total{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"})"
    }
   ]
  },
  {
   "title": "Resource Rejection Details",
   "type": "table",
   "description": "This table is a summary of resource rejection for all nodes. With this you can get the resource rejection count for each node. It captures just the last values for each node.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(node_name,pool_name)(increase(vertica_resource_rejections_total{revive_instance_id=~\"$db_name\",pool_name=~\"$pool_name\"}[5m])) or on() vector(0)",
     "legendFormat": "Resource Rejections"
    }
   ]
  },
  {
   "title": "Disk Storage Activity on node $node_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Total Disk Storage",
   "type": "stat",
   "description": "Given a selected node, it displays the disk storage in total for each storage usage.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(storage_usage) (vertica_disk_storage_total_mb{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "{{storage_usage}}"
    }
   ]
  },
  {
   "title": "Disk Storage Used",
   "type": "stat",
   "description": "Given a selected node, it displays the current disk storage usage for each storage usage.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(storage_usage)(vertica_disk_storage_used_mb{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "{{storage_usage}}"
    }
   ]
  },
  {
   "title": "Disk Storage Available ",
   "type": "gauge",
   "description": "Given a selected node, it displays the percentage of current disk storage available for each storage usage.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(storage_usage) (vertica_disk_storage_free_percent{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "{{storage_usage}}"
    }
   ]
  },
  {
   "title": "Storage Location Performance on node $node_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Throughput in MB/sec",
   "type": "timeseries",
   "description": "Measures each storage location's performance in MB/s.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by(storage_usage) (vertica_disk_storage_throughput_mb_per_second{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "{{storage_usage}}"
    }
   ]
  },
  {
   "title": "Latency in seeks/sec",
   "type": "timeseries",
   "description": "Measures each storage location's performance in seeks/s.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "seeks/sec" } },
   "targets": [
    {
     "expr": "sum by(storage_usage)(vertica_disk_storage_latency_seek_per_second{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "{{storage_usage}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Percentage",
   "type": "timeseries",
   "description": "The percentage of disk space used for each storage usage, over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "100 - sum by(storage_usage) (vertica_disk_storage_free_percent{revive_instance_id=~\"$db_name\",node_name=~\"$node_name\"})",
     "legendFormat": "{{storage_usage}}"
    }
   ]
  }
 ]
}